# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/j/Desktop/c/stream-processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/j/Desktop/c/stream-processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/Desktop/c/stream-processor/CMakeFiles /home/j/Desktop/c/stream-processor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/Desktop/c/stream-processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stream_processor_example

# Build rule for target.
stream_processor_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stream_processor_example
.PHONY : stream_processor_example

# fast build rule for target.
stream_processor_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor_example.dir/build.make CMakeFiles/stream_processor_example.dir/build
.PHONY : stream_processor_example/fast

#=============================================================================
# Target rules for targets named stream_processor

# Build rule for target.
stream_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stream_processor
.PHONY : stream_processor

# fast build rule for target.
stream_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor.dir/build.make CMakeFiles/stream_processor.dir/build
.PHONY : stream_processor/fast

#=============================================================================
# Target rules for targets named hash_cache_example

# Build rule for target.
hash_cache_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hash_cache_example
.PHONY : hash_cache_example

# fast build rule for target.
hash_cache_example/fast:
	$(MAKE) $(MAKESILENT) -f build/hash-cache/CMakeFiles/hash_cache_example.dir/build.make build/hash-cache/CMakeFiles/hash_cache_example.dir/build
.PHONY : hash_cache_example/fast

#=============================================================================
# Target rules for targets named hash_optimal

# Build rule for target.
hash_optimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hash_optimal
.PHONY : hash_optimal

# fast build rule for target.
hash_optimal/fast:
	$(MAKE) $(MAKESILENT) -f build/hash-cache/CMakeFiles/hash_optimal.dir/build.make build/hash-cache/CMakeFiles/hash_optimal.dir/build
.PHONY : hash_optimal/fast

#=============================================================================
# Target rules for targets named hash_cache

# Build rule for target.
hash_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hash_cache
.PHONY : hash_cache

# fast build rule for target.
hash_cache/fast:
	$(MAKE) $(MAKESILENT) -f build/hash-cache/CMakeFiles/hash_cache.dir/build.make build/hash-cache/CMakeFiles/hash_cache.dir/build
.PHONY : hash_cache/fast

#=============================================================================
# Target rules for targets named log_example

# Build rule for target.
log_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 log_example
.PHONY : log_example

# fast build rule for target.
log_example/fast:
	$(MAKE) $(MAKESILENT) -f build/log/CMakeFiles/log_example.dir/build.make build/log/CMakeFiles/log_example.dir/build
.PHONY : log_example/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) $(MAKESILENT) -f build/log/CMakeFiles/log.dir/build.make build/log/CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named sync_example

# Build rule for target.
sync_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sync_example
.PHONY : sync_example

# fast build rule for target.
sync_example/fast:
	$(MAKE) $(MAKESILENT) -f build/sync/CMakeFiles/sync_example.dir/build.make build/sync/CMakeFiles/sync_example.dir/build
.PHONY : sync_example/fast

#=============================================================================
# Target rules for targets named sync

# Build rule for target.
sync: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sync
.PHONY : sync

# fast build rule for target.
sync/fast:
	$(MAKE) $(MAKESILENT) -f build/sync/CMakeFiles/sync.dir/build.make build/sync/CMakeFiles/sync.dir/build
.PHONY : sync/fast

#=============================================================================
# Target rules for targets named array_example

# Build rule for target.
array_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 array_example
.PHONY : array_example

# fast build rule for target.
array_example/fast:
	$(MAKE) $(MAKESILENT) -f build/array/CMakeFiles/array_example.dir/build.make build/array/CMakeFiles/array_example.dir/build
.PHONY : array_example/fast

#=============================================================================
# Target rules for targets named array_test

# Build rule for target.
array_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 array_test
.PHONY : array_test

# fast build rule for target.
array_test/fast:
	$(MAKE) $(MAKESILENT) -f build/array/CMakeFiles/array_test.dir/build.make build/array/CMakeFiles/array_test.dir/build
.PHONY : array_test/fast

#=============================================================================
# Target rules for targets named array

# Build rule for target.
array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 array
.PHONY : array

# fast build rule for target.
array/fast:
	$(MAKE) $(MAKESILENT) -f build/array/CMakeFiles/array.dir/build.make build/array/CMakeFiles/array.dir/build
.PHONY : array/fast

#=============================================================================
# Target rules for targets named dict_example

# Build rule for target.
dict_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dict_example
.PHONY : dict_example

# fast build rule for target.
dict_example/fast:
	$(MAKE) $(MAKESILENT) -f build/dict/CMakeFiles/dict_example.dir/build.make build/dict/CMakeFiles/dict_example.dir/build
.PHONY : dict_example/fast

#=============================================================================
# Target rules for targets named dict_test

# Build rule for target.
dict_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dict_test
.PHONY : dict_test

# fast build rule for target.
dict_test/fast:
	$(MAKE) $(MAKESILENT) -f build/dict/CMakeFiles/dict_test.dir/build.make build/dict/CMakeFiles/dict_test.dir/build
.PHONY : dict_test/fast

#=============================================================================
# Target rules for targets named dict

# Build rule for target.
dict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dict
.PHONY : dict

# fast build rule for target.
dict/fast:
	$(MAKE) $(MAKESILENT) -f build/dict/CMakeFiles/dict.dir/build.make build/dict/CMakeFiles/dict.dir/build
.PHONY : dict/fast

#=============================================================================
# Target rules for targets named json_example

# Build rule for target.
json_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json_example
.PHONY : json_example

# fast build rule for target.
json_example/fast:
	$(MAKE) $(MAKESILENT) -f build/json/CMakeFiles/json_example.dir/build.make build/json/CMakeFiles/json_example.dir/build
.PHONY : json_example/fast

#=============================================================================
# Target rules for targets named json_test

# Build rule for target.
json_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json_test
.PHONY : json_test

# fast build rule for target.
json_test/fast:
	$(MAKE) $(MAKESILENT) -f build/json/CMakeFiles/json_test.dir/build.make build/json/CMakeFiles/json_test.dir/build
.PHONY : json_test/fast

#=============================================================================
# Target rules for targets named json

# Build rule for target.
json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json
.PHONY : json

# fast build rule for target.
json/fast:
	$(MAKE) $(MAKESILENT) -f build/json/CMakeFiles/json.dir/build.make build/json/CMakeFiles/json.dir/build
.PHONY : json/fast

#=============================================================================
# Target rules for targets named json_test_lib

# Build rule for target.
json_test_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json_test_lib
.PHONY : json_test_lib

# fast build rule for target.
json_test_lib/fast:
	$(MAKE) $(MAKESILENT) -f build/json/CMakeFiles/json_test_lib.dir/build.make build/json/CMakeFiles/json_test_lib.dir/build
.PHONY : json_test_lib/fast

#=============================================================================
# Target rules for targets named node_example

# Build rule for target.
node_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node_example
.PHONY : node_example

# fast build rule for target.
node_example/fast:
	$(MAKE) $(MAKESILENT) -f build/node/CMakeFiles/node_example.dir/build.make build/node/CMakeFiles/node_example.dir/build
.PHONY : node_example/fast

#=============================================================================
# Target rules for targets named node

# Build rule for target.
node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node
.PHONY : node

# fast build rule for target.
node/fast:
	$(MAKE) $(MAKESILENT) -f build/node/CMakeFiles/node.dir/build.make build/node/CMakeFiles/node.dir/build
.PHONY : node/fast

#=============================================================================
# Target rules for targets named parallel_example

# Build rule for target.
parallel_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parallel_example
.PHONY : parallel_example

# fast build rule for target.
parallel_example/fast:
	$(MAKE) $(MAKESILENT) -f build/parallel/CMakeFiles/parallel_example.dir/build.make build/parallel/CMakeFiles/parallel_example.dir/build
.PHONY : parallel_example/fast

#=============================================================================
# Target rules for targets named parallel

# Build rule for target.
parallel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parallel
.PHONY : parallel

# fast build rule for target.
parallel/fast:
	$(MAKE) $(MAKESILENT) -f build/parallel/CMakeFiles/parallel.dir/build.make build/parallel/CMakeFiles/parallel.dir/build
.PHONY : parallel/fast

#=============================================================================
# Target rules for targets named queue_example

# Build rule for target.
queue_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 queue_example
.PHONY : queue_example

# fast build rule for target.
queue_example/fast:
	$(MAKE) $(MAKESILENT) -f build/queue/CMakeFiles/queue_example.dir/build.make build/queue/CMakeFiles/queue_example.dir/build
.PHONY : queue_example/fast

#=============================================================================
# Target rules for targets named queue_test

# Build rule for target.
queue_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 queue_test
.PHONY : queue_test

# fast build rule for target.
queue_test/fast:
	$(MAKE) $(MAKESILENT) -f build/queue/CMakeFiles/queue_test.dir/build.make build/queue/CMakeFiles/queue_test.dir/build
.PHONY : queue_test/fast

#=============================================================================
# Target rules for targets named queue

# Build rule for target.
queue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 queue
.PHONY : queue

# fast build rule for target.
queue/fast:
	$(MAKE) $(MAKESILENT) -f build/queue/CMakeFiles/queue.dir/build.make build/queue/CMakeFiles/queue.dir/build
.PHONY : queue/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor_example.dir/build.make CMakeFiles/stream_processor_example.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor_example.dir/build.make CMakeFiles/stream_processor_example.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor_example.dir/build.make CMakeFiles/stream_processor_example.dir/main.c.s
.PHONY : main.c.s

stream_processor.o: stream_processor.c.o
.PHONY : stream_processor.o

# target to build an object file
stream_processor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor.dir/build.make CMakeFiles/stream_processor.dir/stream_processor.c.o
.PHONY : stream_processor.c.o

stream_processor.i: stream_processor.c.i
.PHONY : stream_processor.i

# target to preprocess a source file
stream_processor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor.dir/build.make CMakeFiles/stream_processor.dir/stream_processor.c.i
.PHONY : stream_processor.c.i

stream_processor.s: stream_processor.c.s
.PHONY : stream_processor.s

# target to generate assembly for a file
stream_processor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_processor.dir/build.make CMakeFiles/stream_processor.dir/stream_processor.c.s
.PHONY : stream_processor.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... array"
	@echo "... array_example"
	@echo "... array_test"
	@echo "... dict"
	@echo "... dict_example"
	@echo "... dict_test"
	@echo "... hash_cache"
	@echo "... hash_cache_example"
	@echo "... hash_optimal"
	@echo "... json"
	@echo "... json_example"
	@echo "... json_test"
	@echo "... json_test_lib"
	@echo "... log"
	@echo "... log_example"
	@echo "... node"
	@echo "... node_example"
	@echo "... parallel"
	@echo "... parallel_example"
	@echo "... queue"
	@echo "... queue_example"
	@echo "... queue_test"
	@echo "... stream_processor"
	@echo "... stream_processor_example"
	@echo "... sync"
	@echo "... sync_example"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stream_processor.o"
	@echo "... stream_processor.i"
	@echo "... stream_processor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

